services:
  es-master-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: es-master-1
    environment:
      - node.name=es-master-1
      - cluster.name=es-cluster
      - node.roles=master
      - discovery.seed_hosts=es-master-2, es-master-3, es-data-1, es-data-2
      - cluster.initial_master_nodes=es-master-1, es-master-2, es-master-3
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastic

  es-master-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: es-master-2
    environment:
      - node.name=es-master-2
      - cluster.name=es-cluster
      - node.roles=master
      - discovery.seed_hosts=es-master-1, es-master-3, es-data-1, es-data-2
      - cluster.initial_master_nodes=es-master-1, es-master-2, es-master-3
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
#    ports:
#      - "9200:9200"
    networks:
      - elastic

  es-master-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: es-master-3
    environment:
      - node.name=es-master-3
      - cluster.name=es-cluster
      - node.roles=master
      - discovery.seed_hosts=es-master-2, es-master-1, es-data-1, es-data-2
      - cluster.initial_master_nodes=es-master-1, es-master-2, es-master-3
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
#    ports:
#      - "9200:9200"
    networks:
      - elastic


  es-data-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: es-data-1
    environment:
      - node.name=es-data-1
      - cluster.name=sklep-cluster
      - node.roles=data,ingest
      - discovery.seed_hosts=es-master-1,es-master-2,es-master-3,es-data-2
      - cluster.initial_master_nodes=es-master-1,es-master-2,es-master-3
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    networks:
      - elastic

  es-data-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: es-data-2
    environment:
      - node.name=es-data-2
      - cluster.name=sklep-cluster
      - node.roles=data,ingest
      - discovery.seed_hosts=es-master-1,es-master-2,es-master-3,es-data-1
      - cluster.initial_master_nodes=es-master-1,es-master-2,es-master-3
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    networks:
      - elastic

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es-data-1:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - elastic